# -*- mode: ruby -*-
# vi: set ft=ruby :


# -------------------------------------------
# set your project name here. bootstrap.sh will get it
# -------------------------------------------
$projectName = "python27"
$djangoName = 'unchained'


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = "http://goo.gl/8kWkm"
  config.vm.box = "Ubuntu Server 12.04 amd64 (with Puppet, Chef and VirtualBox 4.2.1)"

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
     vb.name = $projectName
  end

  # Default to the project directory.
  config.vm.synced_folder "..", "/home/project/" + $projectName

  #HTTP - For Django development
  config.vm.network :forwarded_port, guest: 8000, host: 9999
  #HTTPS
  config.vm.network :forwarded_port, guest: 443, host: 8443

  config.vm.provision :shell, :path => "bootstrap.sh", :args => [$projectName, $djangoName]
end
